version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/fossoreslp/go-easy-websocket
    steps:
      - checkout
      - run: go get
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: go get -u github.com/mattn/goveralls
      - run: mkdir test-results
      - run:
          name: Run unit tests
          command: go test -v 2>&1 | go-junit-report > test-results/report.xml
      - run:
          name: Coverage profile
          command: goveralls -show -service=circle-ci -repotoken $COVERALLS_TOKEN
      - run:
          name: go vet
          command: go vet
      - store_test_results:
          path: test-results